[package]
name = "smirk"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "A chemically complete tokenizer for OpenSMILES"
authors = [
    "Alexius Wadell <awadell@umich.edu>",
    "Anoushka Bhutani",
]
readme = "README.md"
repository = "https://github.com/BattModels/smirk"

[lib]
name = "smirk"
crate-type = ["cdylib"]

[dependencies]
clap = "4.5.1"
const_format = "0.2.32"
derive_builder = "0.20.0"
dict_derive = "0.6.0"
either = "1.13.0"
macro_rules_attribute = "0.2.0"
once_cell = "1.19.0"
paste = "1.0.14"
pyo3 = { version = "^0.23", features = ["extension-module"] }
regex = "1.10.3"
serde = "1.0.197"
serde_json = "1.0.114"
serde_with = "3.8.0"
tokenizers = { version = "^0.21"}

[dev-dependencies]
tempfile = "3.10.1"
