version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
