[project]
name = "smirk"
requires-python = ">=3.9"
dynamic = ["version", "readme", "license"]
authors = [
    { name="Alexius Wadell", email="awadell@umich.edu" },
    { name="Anoushka Bhutani" },
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "transformers >=4.40,<5",
]

[project.urls]
source = "https://github.com/BattModels/smirk"
homepage = "https://eeg.engin.umich.edu/smirk"
documentation = "https://eeg.engin.umich.edu/smirk"
issues = "https://github.com/BattModels/smirk/issues"
changelog = "https://github.com/BattModels/smirk/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "pytest~=8.3",
    "parameterized==0.9.0",
    "ruff~=0.9.4",
    "torch~=2.0",
    "numpy~=2.0",
    "pre-commit~=4.1.0",
    "maturin~=1.7",
]
docs = [
    "furo==2024.8.6",
    "jupyter~=1.1",
    "myst-nb~=1.2.0",
    "sphinx~=7.4",
    "sphinx-argparse==0.4.0",
    "sphinx-autobuild==2024.10.3",
    "sphinx-copybutton==0.5.2",
    "accelerate~=1.3",
    "datasets~=3.3",
    "torch~=2.0",
    "rdkit==2024.9.5",
    "transformers~=4.48.2",
]

[build-system]
build-backend = "maturin"
requires = ["maturin~=1.7"]

[tool.maturin]
python-source = "python"
include = [ "./python/smirk/vocab_smiles.json", "./python/smirk/vocab_selfies.json" ]
