name: docs
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - run: uv sync --group docs
      - run: uv run --group docs --with pip sphinx-build docs build/html
      - uses: actions/upload-pages-artifact@v4
        with:
          path: build/html/
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
