name: docs
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - run: uv sync --group docs
      - run: uv run --group docs --with pip sphinx-build docs build/html
      - uses: actions/upload-artifact@v4
        with:
          name: smirk-docs
          path: build/html
